create view marketingdata_prod.warehouse.next_uk_nextads_model_scores_latest as
select
    coalesce(div.account_number, kids.account_number, home.account_number) as account_number,

    div.WW as div_womens,
    div.MW as div_mens,
    div.GW as div_girls,
    div.BW as div_boys,
    div.NB as div_baby,
    div.BL as div_beauty,
    div.HF as div_homefurniture,
    div.HW as div_home,
    div.WB as div_womensbrands,
    div.MB as div_mensbrands,
    div.GB as div_girlsbrands,
    div.BB as div_babybrands,
    div.WP as div_womenspremium,
    div.MP as div_menspremium,
    div.WS as div_womenssports,
    div.MS as div_menssports,
    div.GS as div_girlssports,
    div.BS as div_boyssports,
    div.BRM as div_bedroom,
    div.LRM as div_livingroom,
    div.DRM as div_diningroom,
    div.KIT as div_kitchen,
    div.GDN as div_garden,
    div.HMO as div_ornaments,
    div.BTH as div_bathroom,
    div.LGT as div_lighting,
    div.HMF as div_homefurnishings,

    clr.clearance,

    ww.WW_adidas as womens_adidas,
    ww.WW_barbour as womens_barbour,
    ww.WW_converse as womens_converse,
    ww.WW_flt as womens_flt,
    ww.WW_gap as womens_gap,
    ww.WW_joules as womens_joules,
    ww.WW_linzi as womens_linzi,
    ww.WW_lipsy as womens_lipsy,
    ww.WW_loveroses as womens_loveroses,
    ww.WW_mintvelvet as womens_mintvelvet,
    ww.WW_next as womens_next,
    ww.WW_nike as womens_nike,
    ww.WW_phaseeight as womens_phaseeight,
    ww.WW_pourmoi as womens_pourmoi,
    ww.WW_reiss as womens_reiss,
    ww.WW_roman as womens_roman,
    ww.WW_superdry as womens_superdry,
    ww.WW_tedbaker as womens_tedbaker,
    ww.WW_vs as womens_vs,
    ww.WW_yourscurve as womens_yourscurve,
    ww.WW_bags as womens_bags,
    ww.WW_blouses as womens_blouses,
    ww.WW_boots as womens_boots,
    ww.WW_bras as womens_bras,
    ww.WW_knickers as womens_knickers,
    ww.WW_coats as womens_coats,
    ww.WW_dresses as womens_dresses,
    ww.WW_hats as womens_hats,
    ww.WW_holiday as womens_holiday,
    ww.WW_hoodies as womens_hoodies,
    ww.WW_jeans as womens_jeans,
    ww.WW_jewellery as womens_jewellery,
    ww.WW_jumpers as womens_jumpers,
    ww.WW_jumpsuits as womens_jumpsuits,
    ww.WW_leggings as womens_leggings,
    ww.WW_lingerie as womens_lingerie,
    ww.WW_nightwear as womens_nightwear,
    ww.WW_sandals as womens_sandals,
    ww.WW_shoes as womens_shoes,
    ww.WW_shorts as womens_shorts,
    ww.WW_skirts as womens_skirts,
    ww.WW_sports as womens_sports,
    ww.WW_suits as womens_suits,
    ww.WW_swim as womens_swim,
    ww.WW_tailoring as womens_tailoring,
    ww.WW_tops as womens_tops,
    ww.WW_trainers as womens_trainers,
    ww.WW_trousers as womens_trousers,
    ww.ww_run as womens_run,
    ww.ww_casual as womens_casual,
    ww.ww_multilingerie as womens_multilingerie,
    ww.ww_party as womens_party,
    ww.ww_holidayshop as womens_holidayshop,
    ww.ww_parisianchic as womens_parisianchic,
    ww.ww_rochelle as womens_rochelle,
    ww.wwr_self as womens_self,
    ww.ww_workwear as womens_workwear,
    ww.ww_wideshoes as womens_wideshoes,
    ww.ww_blazers as womens_blazers,
    ww.ww_essentials as womens_essentials,
    ww.ww_elements as womens_elements,
    ww.ww_premium as womens_premium,
    ww.ww_animal as womens_animal,
    ww.ww_blues as womens_blues,
    ww.ww_crochet as womens_crochet,
    ww.ww_floral as womens_floral,
    ww.ww_glam as womens_glam,
    ww.ww_linen as womens_linen,
    ww.ww_maxi as womens_maxi,
    ww.ww_print as womens_print,
    ww.ww_summerdress as womens_summerdress,
    ww.womensdd as womens_dd,
    ww.ww_monsoon as womens_monsoon,
    ww.ww_riverisland as womens_riverisland,
    ww.ww_friendslikethese as womens_friendslikethese,
    ww.ww_loveandroses as womens_loveandroses,
    ww.ww_fatface as womens_fatface,
    ww.ww_threadbare as womens_threadbare,
    ww.ww_tommyhilfiger as womens_tommyhilfiger,
    ww.ww_lauraashley as womens_lauraashley,
    ww.ww_regatta as womens_regatta,
    ww.ww_mango as womens_mango,
    ww.ww_levis as womens_levis,
    ww.ww_boden as womens_boden,
    ww.ww_tog24 as womens_tog24,
    ww.ww_allsaints as womens_allsaints,
    ww.ww_bananarepublic as womens_bananarepublic,
    ww.ww_crocs as womens_crocs,
    ww.ww_frenchconnection as womens_frenchconnection,
    ww.ww_newbalance as womens_newbalance,
    ww.ww_bbytedbaker as womens_bbytedbaker,
    ww.ww_accessorize as womens_accessorize,
    ww.ww_birkenstock as womens_birkenstock,
    ww.ww_carvela as womens_carvela,
    ww.ww_curveslikethese as womens_curveslikethese,
    ww.ww_hush as womens_hush,
    ww.ww_triumph as womens_triumph,
    ww.ww_sosandar as womens_sosandar,
    ww.ww_joliemoi as womens_joliemoi,
    ww.ww_myleeneklass as womens_myleeneklass,
    ww.ww_calvinklein as womens_calvinklein,
    ww.ww_ralphlauren as womens_ralphlauren,
    ww.ww_feminineandpretty as womens_feminineandpretty,
    ww.ww_heritagecasual as womens_heritagecasual,
    ww.ww_bridal as womens_bridal,
    ww.ww_bridesmaid as womens_bridesmaid,
    ww.ww_prom as womens_prom,
    ww.ww_modest as womens_modest,
    ww.ww_athleisure as womens_athleisure,
    ww.ww_bardot as womens_bardot,
    ww.ww_leather as womens_leather,
    ww.ww_widelegjeans as womens_widelegjeans,
    ww.ww_straightlegjeans as womens_straightlegjeans,
    ww.ww_skinnyjeans as womens_skinnyjeans,
    ww.ww_flaredbootcutjeans as womens_flaredbootcutjeans,

    mw.adidas as mens_adidas,
    mw.superdry as mens_superdry,
    mw.swim as mens_swim,
    mw.threadbare as mens_threadbare,
    mw.ties as mens_ties,
    mw.tommyhilf as mens_tommyhilf,
    mw.trainers as mens_trainers,
    mw.Trousers as mens_Trousers,
    mw.Tshirts as mens_Tshirts,
    mw.underarmour as mens_underarmour,
    mw.underwear as mens_underwear,
    mw.vests as mens_vests,
    mw.bags as mens_bags,
    mw.barbour as mens_barbour,
    mw.belts as mens_belts,
    mw.boots as mens_boots,
    mw.boss as mens_boss,
    mw.ck as mens_ck,
    mw.fatface as mens_fatface,
    mw.gap as mens_gap,
    mw.hats as mens_hats,
    mw.hoodies as mens_hoodies,
    mw.jacketscoats as mens_jacketscoats,
    mw.Jeans as mens_Jeans,
    mw.joggers as mens_joggers,
    mw.jumpers as mens_jumpers,
    mw.levis as mens_levis,
    mw.lylescott as mens_lylescott,
    mw.Next as mens_Next,
    mw.nightwear as mens_nightwear,
    mw.nike as mens_nike,
    mw.northface as mens_northface,
    mw.Polo as mens_Polo,
    mw.ralphlauren as mens_ralphlauren,
    mw.reiss as mens_reiss,
    mw.riverisland as mens_riverisland,
    mw.sandals as mens_sandals,
    mw.Shirts as mens_Shirts,
    mw.shoes as mens_shoes,
    mw.Shorts as mens_Shorts,
    mw.Socks as mens_Socks,
    mw.suits as mens_suits,
    mw.mw_signature as mens_signature,
    mw.mw_casual as mens_casual,
    mw.mw_formal as mens_formal,
    mw.mw_edit as mens_edit,
    mw.mw_marvin as mens_marvin,
    mw.mw_tog24 as mens_tog24,
    mw.mw_regatta as mens_regatta,
    mw.mw_moss as mens_moss,
    mw.mw_joules as mens_joules,
    mw.mw_hugo as mens_hugo,
    mw.mw_golf as mens_golf,
    mw.mw_fredperry as mens_fredperry,
    mw.mw_allsaints as mens_allsaints,
    
    kids.baby_bodysuits,
    kids.baby_dresses,
    kids.baby_gap,
    kids.baby_hats,
    kids.baby_jojo_maman_bebe,
    kids.baby_jumpsuits,
    kids.baby_knitwear,
    kids.baby_sandals,
    kids.baby_sets,
    kids.baby_sleepbags,
    kids.baby_sleepsuits,
    kids.baby_summer_dresses,
    kids.baby_swimwear,
    kids.baby_tshirts_and_tops,
    kids.boys_adidas,
    kids.boys_angel_and_rocket,
    kids.boys_ted_baker,
    kids.boys_boden,
    kids.boys_boss,
    kids.boys_clarks,
    kids.boys_converse,
    kids.boys_crocs,
    kids.boys_fatface,
    kids.boys_gap,
    kids.boys_jojo_maman_bebe,
    kids.boys_joules,
    kids.boys_kickers,
    kids.boys_nike,
    kids.boys_paul_smith,
    kids.boys_ralph_lauren,
    kids.boys_reebok,
    kids.boys_reiss,
    kids.boys_schuh,
    kids.boys_smallsaints,
    kids.boys_smiggle,
    kids.boys_start_rite,
    kids.boys_tommy_hilfiger,
    kids.girls_adidas,
    kids.girls_angel_and_rocket,
    kids.girls_ted_baker,
    kids.girls_boden,
    kids.girls_clarks,
    kids.girls_converse,
    kids.girls_crocs,
    kids.girls_fatface,
    kids.girls_gap,
    kids.girls_jojo_maman_bebe,
    kids.girls_joules,
    kids.girls_kickers,
    kids.girls_lipsy,
    kids.girls_monsoon,
    kids.girls_nike,
    kids.girls_ralph_lauren,
    kids.girls_reebok,
    kids.girls_reiss,
    kids.girls_schuh,
    kids.girls_smallsaints,
    kids.girls_smiggle,
    kids.girls_start_rite,
    kids.girls_tommy_hilfiger,
    kids.older_girls_bags as girls_older_bags,
    kids.older_girls_boots as girls_older_boots,
    kids.older_girls_coats_and_jackets as girls_older_coats_and_jackets,
    kids.older_girls_dresses as girls_older_dresses,
    kids.older_girls_hoodies as girls_older_hoodies,
    kids.older_girls_jeans as girls_older_jeans,
    kids.older_girls_joggers as girls_older_joggers,
    kids.older_girls_jumpsuits as girls_older_jumpsuits,
    kids.older_girls_knitwear as girls_older_knitwear,
    kids.older_girls_leggings as girls_older_leggings,
    kids.older_girls_pyjamas as girls_older_pyjamas,
    kids.older_girls_sandals as girls_older_sandals,
    kids.older_girls_school_shoes as girls_older_school_shoes,
    kids.older_girls_sets as girls_older_sets,
    kids.older_girls_shoes as girls_older_shoes,
    kids.older_girls_shorts as girls_older_shorts,
    kids.older_girls_skirts as girls_older_skirts,
    kids.older_girls_sport as girls_older_sport,
    kids.older_girls_summer_dresses as girls_older_summer_dresses,
    kids.older_girls_sweatshirts as girls_older_sweatshirts,
    kids.older_girls_swimwear as girls_older_swimwear,
    kids.older_girls_tshirts_and_tops as girls_older_tshirts_and_tops,
    kids.older_girls_trainers as girls_older_trainers,
    kids.older_girls_uniform as girls_older_uniform,
    kids.younger_girls_bags as girls_younger_bags,
    kids.younger_girls_boots as girls_younger_boots,
    kids.younger_girls_coats_and_jackets as girls_younger_coats_and_jackets,
    kids.younger_girls_dresses as girls_younger_dresses,
    kids.younger_girls_hoodies as girls_younger_hoodies,
    kids.younger_girls_jeans as girls_younger_jeans,
    kids.younger_girls_joggers as girls_younger_joggers,
    kids.younger_girls_jumpsuits as girls_younger_jumpsuits,
    kids.younger_girls_knitwear as girls_younger_knitwear,
    kids.younger_girls_leggings as girls_younger_leggings,
    kids.younger_girls_pyjamas as girls_younger_pyjamas,
    kids.younger_girls_sandals as girls_younger_sandals,
    kids.younger_girls_school_shoes as girls_younger_school_shoes,
    kids.younger_girls_sets as girls_younger_sets,
    kids.younger_girls_shoes as girls_younger_shoes,
    kids.younger_girls_shorts as girls_younger_shorts,
    kids.younger_girls_skirts as girls_younger_skirts,
    kids.younger_girls_sport as girls_younger_sport,
    kids.younger_girls_summer_dresses as girls_younger_summer_dresses,
    kids.younger_girls_sweatshirts as girls_younger_sweatshirts,
    kids.younger_girls_swimwear as girls_younger_swimwear,
    kids.younger_girls_tshirts_and_tops as girls_younger_tshirts_and_tops,
    kids.younger_girls_trainers as girls_younger_trainers,
    kids.younger_girls_uniform as girls_younger_uniform,
    kids.older_boys_bags as boys_older_bags,
    kids.older_boys_coats_and_jackets as boys_older_coats_and_jackets,
    kids.older_boys_hoodies as boys_older_hoodies,
    kids.older_boys_jeans as boys_older_jeans,
    kids.older_boys_joggers as boys_older_joggers,
    kids.older_boys_knitwear as boys_older_knitwear,
    kids.older_boys_polo_shirts as boys_older_polo_shirts,
    kids.older_boys_pyjamas as boys_older_pyjamas,
    kids.older_boys_sandals as boys_older_sandals,
    kids.older_boys_school_shoes as boys_older_school_shoes,
    kids.older_boys_sets as boys_older_sets,
    kids.older_boys_shirts as boys_older_shirts,
    kids.older_boys_shoes as boys_older_shoes,
    kids.older_boys_shorts as boys_older_shorts,
    kids.older_boys_smartwear as boys_older_smartwear,
    kids.older_boys_sport as boys_older_sport,
    kids.older_boys_suits as boys_older_suits,
    kids.older_boys_sweatshirts as boys_older_sweatshirts,
    kids.older_boys_swimwear as boys_older_swimwear,
    kids.older_boys_tshirts_and_tops as boys_older_tshirts_and_tops,
    kids.older_boys_trainers as boys_older_trainers,
    kids.older_boys_trousers as boys_older_trousers,
    kids.older_boys_uniform as boys_older_uniform,
    kids.younger_boys_bags as boys_younger_bags,
    kids.younger_boys_coats_and_jackets as boys_younger_coats_and_jackets,
    kids.younger_boys_hoodies as boys_younger_hoodies,
    kids.younger_boys_jeans as boys_younger_jeans,
    kids.younger_boys_joggers as boys_younger_joggers,
    kids.younger_boys_knitwear as boys_younger_knitwear,
    kids.younger_boys_polo_shirts as boys_younger_polo_shirts,
    kids.younger_boys_pyjamas as boys_younger_pyjamas,
    kids.younger_boys_sandals as boys_younger_sandals,
    kids.younger_boys_school_shoes as boys_younger_school_shoes,
    kids.younger_boys_sets as boys_younger_sets,
    kids.younger_boys_shirts as boys_younger_shirts,
    kids.younger_boys_shoes as boys_younger_shoes,
    kids.younger_boys_shorts as boys_younger_shorts,
    kids.younger_boys_smartwear as boys_younger_smartwear,
    kids.younger_boys_sport as boys_younger_sport,
    kids.younger_boys_suits as boys_younger_suits,
    kids.younger_boys_sweatshirts as boys_younger_sweatshirts,
    kids.younger_boys_swimwear as boys_younger_swimwear,
    kids.younger_boys_tshirts_and_tops as boys_younger_tshirts_and_tops,
    kids.younger_boys_trainers as boys_younger_trainers,
    kids.younger_boys_trousers as boys_younger_trousers,
    kids.younger_boys_uniform as boys_younger_uniform,
    kids.boys_icons,
    kids.boys_traditional,
    kids.boys_gamer_urban,
    kids.boys_tv_film,
    kids.boys_bold_skandi,
    kids.boys_neutral_skandi,
    kids.boys_baby_boutique,
    kids.girls_timelesspretty,
    kids.girls_icons,
    kids.girls_glam,
    kids.girls_urban,
    kids.girls_tv_film,
    kids.girls_bold_skandi,
    kids.girls_neutral_skandi,
    kids.girls_baby_boutique,

    home.animalhomeware as home_animalhomeware,
    home.assembled as home_assembled,
    home.autumndecor as home_autumndecor,
    home.boldchichomeware as home_boldchichomeware,
    home.cath_kidston as home_cath_kidston,
    home.clarke_and_clarke as home_clarke_and_clarke,
    home.cosy_home as home_cosy_home,
    home.collectionluxe as home_collectionluxe,
    home.countryhomeware as home_countryhomeware,
    home.femininechichomeware as home_femininechichomeware,
    home.floral_pattern as home_floral_pattern,
    home.french_connection as home_french_connection,
    home.glass as home_glass,
    home.globalhomeware as home_globalhomeware,
    home.hamishthecow as home_hamishthecow,
    home.home_baby_travel,
    home.home_bedroom_furniture,
    home.home_black_white,
    home.home_blue,
    home.home_bronx,
    home.home_christmas,
    home.home_coffee_and_side_tables,
    home.home_decorative_accessories,
    home.home_flowers,
    home.home_glassware,
    home.home_green,
    home.home_grey,
    home.home_kitchen_electricals,
    home.home_living_room_furniture,
    home.home_made_to_measure,
    home.home_malvern,
    home.home_mamas_and_papas,
    home.home_mattresses,
    home.home_neutral,
    home.home_oliver_bonas,
    home.home_pink,
    home.home_premium_brands,
    home.home_red,
    home.home_rockett_st_george,
    home.home_rugs,
    home.home_utility,
    home.home_valencia,
    home.home_yellow,
    home.homewarebrights as home_homewarebrights,
    home.industrialhomeware as home_industrialhomeware,
    home.japandihomeware as home_japandihomeware,
    home.jasper_conran as home_jasper_conran,
    home.laura_ashley as home_laura_ashley,
    home.lego as home_lego,
    home.luxury_textiles as home_luxury_textiles,
    home.made as home_made,
    home.made_lighting as home_made_lighting,
    home.metal as home_metal,
    home.mirrors as home_mirrors,
    home.monochrome as home_monochrome,
    home.next_home_collections as home_next_home_collections,
    home.nina_campbell as home_nina_campbell,
    home.premium_next_home as home_premium_next_home,
    home.premium_wood as home_premium_wood,
    home.pumpkin as home_pumpkin,
    home.quirkyhomeware as home_quirkyhomeware,
    home.retrohomeware as home_retrohomeware,
    home.scandihomeware as home_scandihomeware,
    home.shabby_chic as home_shabby_chic,
    home.springdecor as home_springdecor,
    home.swoon as home_swoon,
    home.vintagehomeware as home_vintagehomeware,
    home.whitebedding as home_whitebedding,
    home.williammorris as home_williammorris,
    home.wood as home_wood,

    beauty.armani_beauty as beauty_armani_beauty,
    beauty.babyliss as beauty_babyliss,
    beauty.bareminerals as beauty_bareminerals,
    beauty.bath_and_body_works as beauty_bath_and_body_works,
    beauty.baylis_and_harding as beauty_baylis_and_harding,
    beauty.beauty_boxes,
    beauty.beauty_electrical,
    beauty.beauty_gifts,
    beauty.benefit as beauty_benefit,
    beauty.bobbi_brown as beauty_bobbi_brown,
    beauty.boss as beauty_boss,
    beauty.chlo as beauty_chlo,
    beauty.clarins as beauty_clarins,
    beauty.clinique as beauty_clinique,
    beauty.cloud_nine as beauty_cloud_nine,
    beauty.dermalogica as beauty_dermalogica,
    beauty.dyson as beauty_dyson,
    beauty.elemis as beauty_elemis,
    beauty.estee_lauder as beauty_estee_lauder,
    beauty.fragrance_mens as beauty_fragrance_mens,
    beauty.fragrance_womens as beauty_fragrance_womens,
    beauty.ghd as beauty_ghd,
    beauty.iconic as beauty_iconic,
    beauty.it_cosmetics as beauty_it_cosmetics,
    beauty.jimmy_choo as beauty_jimmy_choo,
    beauty.kiehls as beauty_kiehls,
    beauty.lancome as beauty_lancome,
    beauty.laura_mercier as beauty_laura_mercier,
    beauty.lip_oils as beauty_lip_oils,
    beauty.liz_earle as beauty_liz_earle,
    beauty.loccitane as beauty_loccitane,
    beauty.mac as beauty_mac,
    beauty.maison_margiela as beauty_maison_margiela,
    beauty.makeup as beauty_makeup,
    beauty.nars as beauty_nars,
    beauty.neom as beauty_neom,
    beauty.olaplex as beauty_olaplex,
    beauty.rabanne as beauty_rabanne,
    beauty.rituals as beauty_rituals,
    beauty.skincare as beauty_skincare,
    beauty.sun_care as beauty_sun_care,
    beauty.the_inkey_list as beauty_the_inkey_list,
    beauty.the_ordinary as beauty_the_ordinary,
    beauty.tom_ford as beauty_tom_ford,
    beauty.too_faced as beauty_too_faced,
    beauty.travel_minis as beauty_travel_minis,
    beauty.urban_decay as beauty_urban_decay,
    beauty.victorias_secret_beauty as beauty_victorias_secret_beauty,
    beauty.ysl as beauty_ysl

from marketingdata_prod.warehouse.next_uk_division_model_latest as div

full outer join marketingdata_prod.warehouse.next_uk_kids_category_model_latest kids
    on div.account_number = kids.account_number
full outer join marketingdata_prod.warehouse.next_uk_home_category_model_latest as home
    on coalesce(div.account_number, kids.account_number) = home.account_number

left join marketingdata_prod.warehouse.next_uk_clearance_model_latest as clr
    on div.account_number = clr.account_number
left join marketingdata_prod.warehouse.next_uk_nextads_model_scores_womens_latest as ww
    on div.account_number = ww.account_number
left join marketingdata_prod.warehouse.next_uk_nextads_model_scores_mens_latest as mw
    on div.account_number = mw.account_number
left join marketingdata_prod.warehouse.next_uk_beauty_category_model_latest as beauty
    on div.account_number = beauty.account_number
