create table {catalog}.{schema}.{client}_nextads_theme_affinity_predict_complete (
    reference_date date not null,
    account_number string not null,
    theme_clean string not null,
    algo_atbs5__lift_top10 double,
    algo_baskets1__cs_top10 double,
    algo_baskets5__freq12_top10 double,
    algo_baskets5__lift_top10 double,
    algo_baskets5__cs_top10 double,
    algo_baskets5__freq12_norm_top10 double,
    algo_views5__lift_top10 double,
    algo_views5__cs_top10 double,
    views_behavior__recency double,
    views_behavior__frequency int,
    views_behavior__recency_rank int,
    atbs_behavior__recency int,
    atbs_behavior__frequency int,
    baskets_behavior__frequency int,
    baskets_behavior__recency_rank int,
    num_retrieval_methods int,
    repurchase_ratio double,
    repurchase_stage string,
    user_total_views int,
    user_view_to_atb_rate double,
    GmaName string,
    Familyconfidence_score double,
    Coupleconfidence_score double,
    Womenswearconfidence_score double,
    Menswearconfidence_score double,
    Beautyconfidence_score double,
    Homeconfidence_score double,
    views_ly_7 int,
    views_ly_30 int,
    baskets_ly_7 int,
    baskets_ly_30 int,
    trending_7x30 double,
    label int,
    views_dates string,
    atbs_dates string,
    baskets_dates string,
    target_dates string,
    rundate date not null,
    month int,
  constraint pk_{client}_nextads_theme_affinity_predict_complete primary key (
    reference_date,
    account_number,
    theme_clean
    )
)
