create table {catalog}.{schema}.{client}_nextads_advert_quality_metrics_latest (
UniqueAdID string NOT NULL, 
Ad_assigned_theme string, 
process_version string NOT NULL, 
Total_items bigint, 
percentage_item_identified_match double, 
percentage_theme_occurrence double, 
total_occurrence_rank int,
percentage_top20_theme_occurrence double, 
top20_occurrence_rank int, 
percentage_primary_theme_occurrence double, 
primary_theme_rank int, 
percentage_top20_primary_theme_occurrence double, 
top20_primary_theme_rank int, 
highest_total_occurrence_theme string, 
highest_total_occurrence_perc double,
highest_top20_occurrence_theme string,
highest_top20_occurrence_perc double, 
highest_primary_theme_occurrence_theme string, 
highest_primary_theme_occurrence_perc double, 
highest_top20_primary_theme_occurrence_theme string,
highest_top20_primary_theme_occurrence_perc double, 
number_ad_image_items bigint, 
number_ad_image_items_matched bigint, 
perc_ad_image_items_matched double, 
number_top_ranked_ad_image_items bigint, 
perc_ad_image_items_matched_top_ranked double ,
 min_item_number_met boolean, 
 perc_theme_occurrence_met boolean,
 perc_top20_theme_occurrence_met boolean, 
 perc_primary_theme_occurrence_met boolean,
 perc_top20_primary_theme_occurrence_met boolean,
 min_perc_item_identified_match_met boolean,
 met_ad_image_items_matched_perc_threshold boolean,
 met_ad_image_items_top_ranked_matched_perc_threshold boolean,
 Validated boolean, 
 ValidationReasons string,
rundate date NOT NULL
)
partitioned by (UniqueAdID, rundate)