CREATE TABLE IF NOT EXISTS {catalog}.{schema}.next_uk_nextads_fs_shopping_bag_click_labels (
  exposure_id STRING NOT NULL,
  impression_event_id STRING NOT NULL,
  label_horizon_days INT NOT NULL,
  account_number STRING NOT NULL,
  advert_id STRING NOT NULL,
  observed_advert_id STRING NOT NULL,
  normalized_observed_advert_id STRING NOT NULL,
  measurement_advert_id STRING NOT NULL,
  assigned_advert_id STRING NOT NULL,
  route STRING NOT NULL,
  platform STRING NOT NULL,
  location STRING NOT NULL,
  placement_rank INT,
  session_date DATE NOT NULL,
  session_id STRING NOT NULL,
  exposure_timestamp TIMESTAMP NOT NULL,
  event_route_tag STRING,
  event_cms_page_id STRING,
  assignment_cms_page_id STRING,
  session_start_timestamp TIMESTAMP NOT NULL,
  device STRING,
  operating_system STRING,
  page_surface STRING NOT NULL,
  treatment STRING,
  assignment_rundate DATE NOT NULL,
  exposure_match_type STRING NOT NULL,
  label_window_end_timestamp TIMESTAMP NOT NULL,
  label_maturity_date DATE NOT NULL,
  label_is_mature BOOLEAN NOT NULL,
  label_cutoff_date DATE NOT NULL,
  impression_count BIGINT NOT NULL,
  click_count BIGINT NOT NULL,
  clicked INT NOT NULL,
  first_click_timestamp TIMESTAMP,
  first_click_id STRING,
  first_click_advert_id STRING,
  first_click_route_tag STRING,
  click_match_type STRING,
  created_at TIMESTAMP,
  updated_at TIMESTAMP,
  CONSTRAINT pk_nextads_fs_shopping_bag_click_labels PRIMARY KEY (
    exposure_id,
    label_horizon_days,
    exposure_timestamp TIMESERIES
  )
)
USING delta
PARTITIONED BY (session_date)
