CREATE TABLE IF NOT EXISTS {catalog}.{schema}.next_uk_nextads_fs_pctr_model_input (
  account_number STRING NOT NULL,
  advert_id STRING NOT NULL,
  reference_date DATE NOT NULL,
  ad_clicked INT,
  treatment_type STRING,
  location INT,
  age INT,
  cash_acc INT,
  advert_ctr DOUBLE,
  device_ctr DOUBLE,
  geo_ctr DOUBLE,
  gender_ctr DOUBLE,
  dod_ctr_change DOUBLE,
  wow_ctr_change DOUBLE,
  number_pages_viewed INT,
  prior_30_day_order_value DOUBLE,
  customer_total_clicks INT,
  customer_total_unique_adverts_clicked INT,
  customer_advert_previous_click_number INT,
  number_clicks_same_algodivision INT,
  advert_impressions INT,
  device_impressions INT,
  geo_impressions INT,
  gender_impressions INT,
  day_impressions INT,
  prior_day_impressions INT,
  view_theme_score DOUBLE,
  perc_order_value_cat_affinity DOUBLE,
  perc_30_day_order_value_cat_affinity DOUBLE,
  perc_order_qty_cat_affinity DOUBLE,
  view_highest_catid_weight DOUBLE,
  view_lift_adjusted DOUBLE,
  purchase_highest_catid_weight DOUBLE,
  purchase_lift_adjusted DOUBLE,
  purchase_theme_affinity DOUBLE,
  created_at TIMESTAMP,
  updated_at TIMESTAMP,
  CONSTRAINT pk_nextads_fs_pctr_model_input PRIMARY KEY (
    account_number,
    advert_id,
    reference_date
  )
)
USING delta
PARTITIONED BY (reference_date)
