default:
  client: next_uk
  control_sheet_v2:
    url: "https://docs.google.com/spreadsheets/d/1UtYh4L22vyxJhSYiD0M1SHb0Vw5eo5RvwqOpR0B4vRI/edit?gid=0#gid=0"
    sheet: "Control Sheet UK"
    date_format: "dd/MM/yyyy"
    date_regex: "([1-2][0-9]|[0][1-9]|[3][0-1])/([0][1-9]|[1][0-2])/([1-9][0-9][0-9]{2})"
    read_schema:
      - ["UniqueAdID", "string", "null"]
      - ["UniqueAdIDPremium", "string", "null"]
      - ["CMSPageID", "string", "null"]
      - ["PotNumber", "string", "null"]
      - ["CampaignNumber", "string", "null"]
      - ["Title", "string", "null"]
      - ["AlgoDivision", "string", "null"]
      - ["TradeDivision", "string", "null"]
      - ["Brand", "string", "null"]
      - ["MASIDToken", "string", "null"]
      - ["plp", "string", "null"]
      - ["for_you", "string", "null"]
      - ["oc", "string", "null"]
      - ["sb", "string", "null"]
      - ["as", "string", "null"]
      - ["HN1", "string", "null"]
      - ["Segment", "string", "null"]
      - ["AdDriver", "string", "null"]
      - ["TemplateName", "string", "null"]
      - ["StartDate", "string", "null"]
      - ["EndDate", "string", "null"]
      - ["Status", "string", "null"]
      - ["AudienceOnly", "string", "null"]
      - ["URL", "string", "null"]
      - ["Items", "string", "null"]
      - ["Tags", "string", "null"]
      - ["Themes", "string", "null"]
      - ["AdVariant", "string", "null"]
  exclusions_sheet:
    url: "https://docs.google.com/spreadsheets/d/1UtYh4L22vyxJhSYiD0M1SHb0Vw5eo5RvwqOpR0B4vRI/edit?gid=0#gid=0"
    sheet: "Exclusions"
    read_schema:
      - ["PageType", "string", "null"]
      - ["Page", "string", "null"]
      - ["Exclude_Campaign", "string", "null"]
