default:
  # Tables written to environment-specific catalog and schema
  tables_write:
    dynaconf_merge: true
    # control sheet tables
    control_sheet_raw_v2: "@format {this.catalog_write}.{this.schema_write}.{this.client}_nextads_control_sheet_raw_v2"
    control_sheet_raw_latest_v2: "@format {this.catalog_write}.{this.schema_write}.{this.client}_nextads_control_sheet_raw_latest_v2"

    control_sheet_v2: "@format {this.catalog_write}.{this.schema_write}.{this.client}_nextads_control_sheet_v2"
    control_sheet_latest_v2: "@format {this.catalog_write}.{this.schema_write}.{this.client}_nextads_control_sheet_latest_v2"

    exclusions_latest: "@format {this.catalog_write}.{this.schema_write}.{this.client}_nextads_exclusions_latest"
    exclusions: "@format {this.catalog_write}.{this.schema_write}.{this.client}_nextads_exclusions"
