# When Dynaconf reads a YAML file with environments=True, it performs a specific loading sequence:
# It looks for your environment block (e.g., dev:).
# It takes every key under that block and "hoists" it to the top level of your settings object.

default:
  job_env: dev
  client: next_uk
  catalog_read: marketingdata_prod
  catalog_write: marketingdata_dev
  schema_read: warehouse
  schema_write: ds_sandbox
  az_st_container_name: adsconfigfeeds
  az_tenant_id: "f009f285-5242-433a-9365-daa1edf145c3"
  secret_key_spn_clientid: "Databricks-Spn-MarketingData-ClientId"
  secret_key_spn_secret: "Databricks-Spn-MarketingData-ClientSecret"
  gcp:
    scope: mktg_gcp
    key: mktg-gcp-service-account-b64-encoded
  webhooks:
    input_warnings: "https://chat.googleapis.com/v1/spaces/AAAA_rFP3_s/messages?key=AIzaSyDdI0hCZtE6vySjMm-WEfRq3CPzqKqqsHI&token=MhMWyk0iva0jwnyeH5pfkVd5m4SVy306sqj4hDqLAhU"

dev:
  catalog_write: marketingdata_dev
  schema_write: "@format {env[USER_SCHEMA]}"
  az_st_account: adsstecmdeveun
  az_st_account_url: "@format https://{this.az_st_account}.blob.core.windows.net/"
  dbutils_secret_scope: "DataIng-KV-MKT-Dev-EUW"
  pii_exponea_next_uk_path: "abfss://next-uk@piiblmrstmktdeveuw.dfs.core.windows.net"

# PREPROD runs in the PROD Databricks workspace but writes validation output to ds_sandbox, not warehouse.
preprod:
  catalog_write: marketingdata_prod
  schema_write: ds_sandbox
  az_st_account: adsstecmppeuw
  az_st_account_url: "@format https://{this.az_st_account}.blob.core.windows.net/"
  dbutils_secret_scope: "DataIng-KV-MKT-Prod-EUW"
  pii_exponea_next_uk_path: "abfss://next-uk@piiblmrstmktprodeuw.dfs.core.windows.net"

prod:
  catalog_write: marketingdata_prod
  schema_write: warehouse
  az_st_account: adsstecmprodeuw
  az_st_account_url: "@format https://{this.az_st_account}.blob.core.windows.net/"
  dbutils_secret_scope: "DataIng-KV-MKT-Prod-EUW"
  pii_exponea_next_uk_path: "abfss://next-uk@piiblmrstmktprodeuw.dfs.core.windows.net"
