CREATE TABLE IF NOT EXISTS {catalog}.{schema}.{client}_nextads_realtime_reranking_preranked_ads (
 UniqueAdID STRING NOT NULL 
 AccountNumber STRING NOT NULL ,
 roamingprofileid STRING NOT NULL ,
 PageType STRING NOT NULL ,
 Score DOUBLE NOT NULL ,
 TriggerScore DOUBLE NOT NULL ,
 Rank INT ,
 FallowControl STRING NOT NULL ,
 HomePageTest1 STRING NOT NULL ,
 ShoppingBagTest1 STRING NOT NULL ,
 OrderCompleteTest1 STRING NOT NULL ,
 LandingPageTest1 STRING NOT NULL ,
 AdHocABTest1 STRING NOT NULL ,
 AdHocABTest2 STRING NOT NULL ,
 AdHocABTest3 STRING NOT NULL ,
 AdHocABTest4 STRING NOT NULL ,
 AdHocABTest5 STRING NOT NULL ,
 AdHocABTest6 STRING NOT NULL ,
 AdHocABTest7 STRING NOT NULL ,
 AdHocABTest8 STRING NOT NULL ,
 AdHocABTest9 STRING NOT NULL ,
 ChampionChallenger STRING NOT NULL ,
 PageTypeIsolation STRING NOT NULL ,
 specialaccountindicator STRING,
 AlgoDivision STRING NOT NULL ,
 IsPremium INT,
 brand STRING, 
 brand_perc_coverage DOUBLE, 
 department STRING, 
 department_perc_coverage DOUBLE, 
 next_category STRING, 
 next_category_perc_coverage DOUBLE, 
 prem_level_brand BOOL ,
 prem_level_brand_perc_coverage DOUBLE ,
 rundate date not null,
    constraint pk_{client}_nextads_realtime_reranking_preranked_ads primary key (
        UniqueAdID,
        roamingprofileid,
        rundate)
)
PARTITIONED BY (roamingprofileid)
