create view marketingdata_prod.warehouse.next_uk_nextads_model_scores_womens_latest as
select
    a.*,
    b.WW_adidas,
    b.WW_barbour,
    b.WW_converse,
    b.WW_flt,
    b.WW_gap,
    b.WW_joules,
    b.WW_linzi,
    b.WW_lipsy,
    b.WW_loveroses,
    b.WW_mintvelvet,
    b.WW_next,
    b.WW_nike,
    b.WW_phaseeight,
    b.WW_pourmoi,
    b.WW_reiss,
    b.WW_roman,
    b.WW_superdry,
    b.WW_tedbaker,
    b.WW_vs,
    b.WW_yourscurve,
    b.WW_bags,
    b.WW_blouses,
    b.WW_boots,
    b.WW_bras,
    b.WW_knickers,
    b.WW_coats,
    b.WW_dresses,
    b.WW_hats,
    b.WW_holiday,
    b.WW_hoodies,
    b.WW_jeans,
    b.WW_jewellery,
    b.WW_jumpers,
    b.WW_jumpsuits,
    b.WW_leggings,
    b.WW_lingerie,
    b.WW_nightwear,
    b.WW_sandals,
    b.WW_shoes,
    b.WW_shorts,
    b.WW_skirts,
    b.WW_sports,
    b.WW_suits,
    b.WW_swim,
    b.WW_tailoring,
    b.WW_tops,
    b.WW_trainers,
    b.WW_trousers,
    c.ww_run,
    c.ww_casual,
    c.ww_multilingerie,
    c.ww_party,
    c.ww_holidayshop,
    c.ww_parisianchic,
    c.ww_rochelle,
    c.wwr_self,
    c.ww_workwear,
    c.ww_wideshoes,
    c.ww_blazers,
    c.ww_essentials,
    c.ww_elements,
    c.ww_premium,
    d.ww_animal,
    d.ww_blues,
    d.ww_crochet,
    d.ww_floral,
    d.ww_glam,
    d.ww_linen,
    d.ww_maxi,
    d.ww_print,
    d.ww_summerdress,
    e.clearance,
    f.womensdd,
    g.ww_monsoon,
    g.ww_riverisland,
    g.ww_friendslikethese,
    g.ww_loveandroses,
    g.ww_fatface,
    g.ww_threadbare,
    g.ww_tommyhilfiger,
    g.ww_lauraashley,
    g.ww_regatta,
    g.ww_mango,
    g.ww_levis,
    g.ww_boden,
    g.ww_tog24,
    g.ww_allsaints,
    g.ww_bananarepublic,
    g.ww_crocs,
    g.ww_frenchconnection,
    g.ww_newbalance,
    g.ww_bbytedbaker,
    g.ww_accessorize,
    g.ww_birkenstock,
    g.ww_carvela,
    g.ww_curveslikethese,
    g.ww_hush,
    g.ww_triumph,
    g.ww_sosandar,
    g.ww_joliemoi,
    g.ww_myleeneklass,
    g.ww_calvinklein,
    g.ww_ralphlauren,
    h.ww_feminineandpretty,
    h.ww_heritagecasual,
    h.ww_bridal,
    h.ww_bridesmaid,
    h.ww_prom,
    h.ww_modest,
    h.ww_athleisure,
    h.ww_bardot,
    h.ww_leather,
    h.ww_widelegjeans,
    h.ww_straightlegjeans,
    h.ww_skinnyjeans,
    h.ww_flaredbootcutjeans
from marketingdata_prod.warehouse.next_uk_division_model_latest a 
inner join marketingdata_prod.warehouse.next_uk_womens_category_model_latest b
    on a.account_number=b.account_number 
inner join marketingdata_prod.warehouse.next_uk_womens_nextads_models_latest c
    on a.account_number=c.account_number 
inner join marketingdata_prod.warehouse.next_uk_womens_styles_models_latest d
    on a.account_number=d.account_number 
inner join marketingdata_prod.warehouse.next_uk_clearance_model_latest e
    on a.account_number=e.account_number 
inner join marketingdata_prod.warehouse.next_uk_womens_dd_model_latest f
    on a.account_number=f.account_number 
inner join marketingdata_prod.warehouse.next_uk_womens_nextads_additional_brand_models_latest g
    on a.account_number=g.account_number 
inner join marketingdata_prod.warehouse.next_uk_womens_nextads_style_models_latest h
    on a.account_number=h.account_number