create table marketingdata_prod.{schema}.{domain}_nextads_control_sheet_latest (
  UniqueAdID string not null,
  UniqueAdIDPremium string,
  PotNumber string not null,
  CampaignNumber string,
  Title string,
  AlgoDivision string,
  TradeDivision string,
  Brand string,
  MASIDToken string,
  Location string,
  Segment string,
  AdDriver string,
  TemplateName string,
  StartDate date,
  EndDate date,
  Models string,
  ModelCombination string,
  TargetingCriteria string,
  URL string,
  ProductURLs string,
  Items string,
  AdCategory string,
  AdMission string,
  AdTrend string,
  AdSubcategory string,
  AdBrandName string,
  AdCampaign string,
  Headline string,
  Subtext string,
  CTA string,
  HeaderColour string,
  TextColour string,
  BackGroundColour string,
  ButtonTextColour string,
  ButtonColour string,
  BrandsLogos string,
  BackgroundImage string,
  MobileImage string,
  FlatJPG string,
  Tags string,
  rundate date not null,
  constraint pk_{domain}_nextads_control_sheet_latest primary key (
    UniqueAdID,
    Location)
)
partitioned by (Location)