CREATE TABLE marketingdata_prod.{schema}.{client}_nextads_control_sheet_raw (
  UniqueAdID STRING NOT NULL,
  UniqueAdIDPremium STRING,
  CMSPageID STRING,
  Realm STRING NOT NULL,
  Territory STRING NOT NULL,
  PotNumber STRING,
  CampaignNumber STRING,
  Title STRING,
  AlgoDivision STRING,
  TradeDivision STRING,
  Brand STRING,
  MASIDToken STRING,
  Segment STRING,
  AdDriver STRING,
  TemplateName STRING,
  StartDate STRING,
  EndDate STRING,
  Status STRING,
  AudienceOnly STRING,
  Models STRING,
  ModelCombination STRING,
  URL STRING,
  ProductURLs STRING,
  Items STRING,
  AdCategory STRING,
  AdMission STRING,
  AdTrend STRING,
  AdSubcategory STRING,
  AdBrandName STRING,
  AdCampaign STRING,
  Headline STRING,
  Subtext STRING,
  CTA STRING,
  HeaderColour STRING,
  TextColour STRING,
  BackGroundColour STRING,
  ButtonTextColour STRING,
  ButtonColour STRING,
  BrandsLogos STRING,
  BackgroundImage STRING,
  MobileImage STRING,
  FlatJPG STRING,
  Tags STRING,
  TargetingAttributes STRING,
  Themes STRING,
  AdVariant STRING,
  HN1 STRING,
  SB1 STRING,
  SB2 STRING,
  OC1 STRING,
  LP1 STRING,
  LP2 STRING,
  LP3 STRING,
  LP4 STRING,
  LP5 STRING,
  LP6 STRING,
  LP7 STRING,
  LP8 STRING,
  LP9 STRING,
  LP10 STRING,
  LP11 STRING,
  PLX STRING,
  PL1 STRING,
  PL2 STRING,
  PL3 STRING,
  PL4 STRING,
  PL5 STRING,
  PL6 STRING,
  PL7 STRING,
  PL8 STRING,
  PL9 STRING,
  PL10 STRING,
  PL11 STRING,
  PL12 STRING,
  PL13 STRING,
  PL14 STRING,
  PL15 STRING,
  PL16 STRING,
  PL17 STRING,
  PL18 STRING,
  PL19 STRING,
  PL20 STRING,
  PL21 STRING,
  PL22 STRING,
  PL23 STRING,
  PL24 STRING,
  PL25 STRING,
  PL26 STRING,
  PL27 STRING,
  PL28 STRING,
  PL29 STRING,
  PL30 STRING,
  PL31 STRING,
  PL32 STRING,
  PL33 STRING,
  PL34 STRING,
  PL35 STRING,
  PL36 STRING,
  PL37 STRING,
  PL38 STRING,
  PL39 STRING,
  PL40 STRING,
  PL61 STRING,
  FY1 STRING,
  rundate DATE,
  CONSTRAINT `pk_{client}_nextads_control_sheet_raw` PRIMARY KEY (`Realm`, `Territory`, `UniqueAdID`))
USING delta
PARTITIONED BY (rundate)
TBLPROPERTIES (
  'delta.enableDeletionVectors' = 'true',
  'delta.feature.deletionVectors' = 'supported',
  'delta.feature.invariants' = 'supported',
  'delta.minReaderVersion' = '3',
  'delta.minWriterVersion' = '7')