create table {catalog}.{schema}.{client}_nextads_control_sheet (
  UniqueAdID STRING NOT NULL,
  UniqueAdIDPremium STRING,
  CMSPageID STRING,
  Realm STRING,
  Territory STRING,
  PotNumber STRING NOT NULL,
  CampaignNumber STRING,
  Title STRING,
  AlgoDivision STRING,
  TradeDivision STRING,
  Brand STRING,
  MASIDToken STRING,
  Location STRING NOT NULL,
  Segment STRING,
  AdDriver STRING,
  TemplateName STRING,
  StartDate DATE,
  EndDate DATE,
  AudienceOnly INT,
  Models STRING,
  ModelCombination STRING,
  TargetingCriteria STRING,
  URL STRING,
  ProductURLs STRING,
  Items STRING,
  AdCategory STRING,
  AdMission STRING,
  AdTrend STRING,
  AdSubcategory STRING,
  AdBrandName STRING,
  AdCampaign STRING,
  Headline STRING,
  Subtext STRING,
  CTA STRING,
  HeaderColour STRING,
  TextColour STRING,
  BackGroundColour STRING,
  ButtonTextColour STRING,
  ButtonColour STRING,
  BrandsLogos STRING,
  BackgroundImage STRING,
  MobileImage STRING,
  FlatJPG STRING,
  Tags STRING,
  TargetingAttributes STRING,
  Themes STRING,
  AdVariant STRING,
  ClusterID STRING,
  Page STRING,
  Screen STRING,
  PageGroup STRING,
  rundate DATE NOT NULL,
  constraint pk_{client}_nextads_control_sheet primary key (
    UniqueAdID,
    Location,
    rundate)
)
partitioned by (rundate)