CREATE OR REPLACE TABLE {catalog}.{schema}.{client}_nextads_control_sheet_raw_latest_v2 (
  UniqueAdID STRING NOT NULL,
  UniqueAdIDPremium STRING,
  CMSPageID STRING,
  PotNumber STRING,
  CampaignNumber STRING,
  Title STRING,
  AlgoDivision STRING,
  TradeDivision STRING,
  Brand STRING,
  MASIDToken STRING,
  plp STRING,
  for_you STRING,
  oc STRING,
  sb STRING,
  as STRING,
  HN1 STRING,
  Segment STRING,
  AdDriver STRING,
  TemplateName STRING,
  StartDate STRING,
  EndDate STRING,
  Status STRING,
  AudienceOnly STRING,
  URL STRING,
  Items STRING,
  Tags STRING,
  Themes STRING,
  AdVariant STRING,
  rundate DATE,
  CONSTRAINT `pk_{client}_nextads_control_sheet_raw_latest_v2` PRIMARY KEY (`UniqueAdID`))
USING delta
TBLPROPERTIES (
  'delta.enableDeletionVectors' = 'true',
  'delta.feature.deletionVectors' = 'supported',
  'delta.feature.invariants' = 'supported',
  'delta.minReaderVersion' = '3',
  'delta.minWriterVersion' = '7')
