CREATE TABLE {catalog}.{schema}.nextads_sort_order_v2 (
    UniqueAdID STRING,
    URL STRING,
    MASIDtoken STRING,
    item_pos BIGINT,
    item STRING,
    UniqueAdIDPremium STRING,
    CMSPageID STRING,
    PotNumber STRING,
    CampaignNumber STRING,
    Title STRING,
    AlgoDivision STRING,
    TradeDivision STRING,
    Brand STRING,
    ProductListingPage STRING,
    ForYouPage STRING,
    CheckoutPage STRING,
    ShoppingBagPage STRING,
    HomePage STRING,
    Segment STRING,
    AdDriver STRING,
    TemplateName STRING,
    StartDate STRING,
    EndDate STRING,
    Status STRING,
    AudienceOnly STRING,
    Items STRING,
    Tags STRING,
    Themes STRING,
    AdVariant STRING,
    rundate DATE,
  constraint pk_{client}_nextads_sort_order_v2 primary key (
    UniqueAdID, item_pos,
    rundate)
    )
partitioned by (rundate)